export interface WorkExperienceData {
  calqiTitle: string
  calqiPeriod: string
  calqiText1: string
  calqiText2: string
  calqiText3: string
  twoPointOTitle: string
  twoPointOPeriod: string
  twoPointOText1: string
  twoPointOBeatTitle: string
  twoPointOBeatDescription: string
  twoPointOBeameryTitle: string
  twoPointOBeameryDescription: string
  twoPointOTroubleshootingPageTitle: string
  twoPointOTroubleshootingPageDescription: string
  twoPointOPocTitle: string
  twoPointOPocDescription: string
  oddballTitle: string
  oddballPeriod: string
  oddballText1: string
  oddballText2: string
  oddballKeyProjects: string
  oddballTheValueChainTitle: string
  oddballTheValueChainDescription: string
  oddballBrightestTitle: string
  oddballBrightestDescription: string
  oddballLincTitle: string
  oddballLincDescription: string
}
